CREATE DATABASE ELEARNING
GO

USE ELEARNING
GO

--SELECT * FROM USUARIOS

--DROP TABLE PRIVILEGIOS
--DROP TABLE INSCRIPCIONES
--DROP TABLE USUARIOS


CREATE TABLE PRIVILEGIOS
(
	ID_PRIVILEGIO		INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_PRIVILEGIO	VARCHAR(50) NOT NULL,
)

CREATE TABLE USUARIOS
(
	ID_USUARIO		INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_USUARIO		VARCHAR(15) NOT NULL,
	NOMBRE			VARCHAR(50),
	APELLIDO		VARCHAR(50),
	EDAD			INT,
	SEXO			VARCHAR(15),
	FECHA_NAC		DATE,
	PAIS			VARCHAR(25),
	DEPTO			VARCHAR(25),
	TELEFONO		VARCHAR(15),
	EMAIL			VARCHAR(50),
	PASWORD			VARBINARY(MAX) NOT NULL,
	IMAGEN			IMAGE,
	ID_PRIVILEGIO	INT,			
	FECHAREGISTRO	DATETIME
)
GO

CREATE TABLE CATEGORIAS
(
	ID_CATEGORIA	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_CAT		VARCHAR(50) NOT NULL
)
GO

CREATE TABLE CURSOS
(
	ID_CURSO		INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_CURSO	VARCHAR(50) NOT NULL,
	ESTADO			BIT,
	ID_CATEGORIA	INT,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
)
GO

CREATE TABLE TEMAS
(
	ID_TEMA			INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_TEMA		VARCHAR(50) NOT NULL,
	ID_CATEGORIA	INT,
	ID_CURSO		INT,
	FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID_CURSO),
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
)

CREATE TABLE CONTENIDOS
(
	ID_CONTENIDO	INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DESCRIPCION		VARCHAR(50) NOT NULL,
	TIPO			VARCHAR(30)NOT NULL,
	ID_CATEGORIA	INT,
	ID_CURSO		INT,
	ID_TEMA			INT,
	FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
	FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID_CURSO),
	FOREIGN KEY(ID_TEMA) REFERENCES TEMAS(ID_TEMA)
)
GO

CREATE TABLE INSCRIPCIONES
(
	ID_INSCRIPCION		INT IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO			INT,
	ID_CURSO			INT,
	ESTADO				VARCHAR(25),
	FECHA_INSCRIPCION	DATETIME,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
)

--DROP TABLE INSCRIPCIONES

--CREATE TABLE ESTADO_USUARIO
--(
--	ID_ESTADO		INT IDENTITY(1,1) PRIMARY KEY,
--	NOMBRE_ESTADO	VARCHAR(25) NOT NULL
--)
--GO

--CREATE TABLE ESTADO_CURSO
--(
--	ID_REGISTRO		INT IDENTITY(1,1) PRIMARY KEY,
--	ID_CURSO		INT,
--	ID_USUARIO		INT,
--	FOREIGN KEY(ID_CURSO) REFERENCES CURSO(ID_CURSO),
--	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
--)
--GO
