USE ELEARNING
GO

ALTER PROCEDURE [dbo].[BUSCAR_CATEGORIA]
(
	@ID_CAT  	 INT,
	@NOMBRE_CAT	VARCHAR(100)
)
AS 
BEGIN
	IF (@ID_CAT>0)
	BEGIN
		IF EXISTS (SELECT * FROM CATEGORIAS WHERE ID_CATEGORIA = @ID_CAT)
			SELECT ID_CATEGORIA,NOMBRE_CAT FROM CATEGORIAS WHERE ID_CATEGORIA = @ID_CAT
		ELSE
			SELECT -1 AS ID_CATEGORIA
	END
	ELSE IF (LEN(RTRIM(@NOMBRE_CAT))>0 OR @NOMBRE_CAT<>'')
	BEGIN
		IF EXISTS(SELECT * FROM CATEGORIAS WHERE NOMBRE_CAT LIKE '%'+@NOMBRE_CAT+'%')
			SELECT ID_CATEGORIA,NOMBRE_CAT FROM CATEGORIAS WHERE NOMBRE_CAT LIKE '%'+@NOMBRE_CAT+'%'
		ELSE
			SELECT -1 AS ID_CATEGORIA
	END
END
