USE ELEARNING
GO

ALTER PROCEDURE [dbo].[BUSCAR_TEMAS]
(
	@ID_TEMA 	 INT,
	@NOMBRE_TEMA	VARCHAR(50) 
)
AS 
BEGIN
	IF (@ID_TEMA>0)
	BEGIN
		IF EXISTS (SELECT * FROM TEMAS WHERE ID_TEMA = @ID_TEMA)
			SELECT   T.ID_TEMA,T.NOMBRE_TEMA,T.ID_CURSO,C.NOMBRE_CURSO,T.ID_CATEGORIA,CAT.NOMBRE_CAT
			FROM TEMAS T
			JOIN CURSOS C ON  C.ID_CATEGORIA=T.ID_CATEGORIA AND  C.ID_CURSO=T.ID_CURSO
			JOIN CATEGORIAS CAT ON C.ID_CATEGORIA=CAT.ID_CATEGORIA
			WHERE ID_TEMA = @ID_TEMA
		ELSE
			SELECT -1 AS ID_TEMA
	END
	ELSE IF (LEN(RTRIM(@NOMBRE_TEMA))>0 OR @NOMBRE_TEMA<>'')
	BEGIN
		IF EXISTS(SELECT * FROM CURSOS WHERE NOMBRE_CURSO LIKE '%'+@NOMBRE_TEMA+'%')
			SELECT   T.ID_TEMA,T.NOMBRE_TEMA,T.ID_CURSO,C.NOMBRE_CURSO,T.ID_CATEGORIA,CAT.NOMBRE_CAT
			FROM TEMAS T
			JOIN CURSOS C ON  C.ID_CATEGORIA=T.ID_CATEGORIA AND  C.ID_CURSO=T.ID_CURSO
			JOIN CATEGORIAS CAT ON C.ID_CATEGORIA=CAT.ID_CATEGORIA
			WHERE NOMBRE_TEMA LIKE '%'+@NOMBRE_TEMA+'%'
		ELSE
			SELECT -1 AS ID_TEMA
	END
END
go