USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_CONTENIDOS]    Script Date: 22/11/2020 16:51:33 ******/
DROP PROCEDURE [dbo].[INSERTAR_CONTENIDOS]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_CONTENIDOS]    Script Date: 22/11/2020 16:51:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[INSERTAR_CONTENIDOS]
(
	@DESCRIPCION	VARCHAR(100),
	@TIPO			VARCHAR(30),
	@ID_CATEGORIA	INT,
	@ID_CURSO		INT,
	@ID_TEMA		INT
)
AS
BEGIN
	INSERT INTO CONTENIDOS(DESCRIPCION, TIPO,ID_CATEGORIA, ID_CURSO, ID_TEMA)
	VALUES(@DESCRIPCION, @TIPO, @ID_CATEGORIA, @ID_CURSO, @ID_TEMA)
END
GO
