USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_TEMAS]    Script Date: 22/11/2020 16:35:51 ******/
DROP PROCEDURE [dbo].[INSERTAR_TEMAS]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_TEMAS]    Script Date: 22/11/2020 16:35:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[INSERTAR_TEMAS]
(
	@NOMBRE_TEMA	VARCHAR(50),
	@ID_CATEGORIA	INT,
	@ID_CURSO		INT
)
AS BEGIN
	INSERT INTO TEMAS(NOMBRE_TEMA, ID_CATEGORIA, ID_CURSO) 
	VALUES(@NOMBRE_TEMA, @ID_CATEGORIA, @ID_CURSO)
END
GO

