USE ELEARNING
GO

CREATE PROCEDURE INSERTAR_USUARIOS
(
	@PATRON			VARCHAR(10),
	@COD_USUARIO	VARCHAR(15),
	@NOMBRE			VARCHAR(50),
	@APELLIDO		VARCHAR(50),
	@EDAD			INT,
	@SEXO			VARCHAR(10),
	@FECHA_NAC		DATE,
	@PAIS			VARCHAR(15),
	@DEPTO			VARCHAR(20),
	@TELEFONO		VARCHAR(15),
	@EMAIL			VARCHAR(25),
	@PASWORD		VARCHAR(15),
	@IMAGEN			IMAGE,
	@ID_PRIVILEGIO	INT
)
AS
BEGIN
	DECLARE @FECHAREGISTRO DATE
	SELECT @FECHAREGISTRO = GETDATE()

	INSERT INTO USUARIOS
	(
		COD_USUARIO,	NOMBRE,		APELLIDO,	EDAD,		SEXO,	FECHA_NAC,	PAIS,
		DEPTO,			TELEFONO,	EMAIL,		PASWORD,	FECHAREGISTRO,
		IMAGEN,			ID_PRIVILEGIO
	)
	VALUES
	(
		@COD_USUARIO,	@NOMBRE,	@APELLIDO,	@EDAD,		@SEXO,	@FECHA_NAC,	@PAIS,
		@DEPTO,			@TELEFONO,	@EMAIL,		ENCRYPTBYPASSPHRASE(@PATRON, @PASWORD),	@FECHAREGISTRO,
		@IMAGEN,		@ID_PRIVILEGIO
	)

END
GO


