USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_CATEGORIAS]    Script Date: 25/11/2020 20:56:20 ******/
DROP PROCEDURE [dbo].[INSERTAR_CATEGORIAS]
GO

/****** Object:  StoredProcedure [dbo].[INSERTAR_CATEGORIAS]    Script Date: 25/11/2020 20:56:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[INSERTAR_CATEGORIAS]
(
	@NOMBRE_CAT		VARCHAR(25)

)
AS BEGIN
	INSERT INTO CATEGORIAS(NOMBRE_CAT) VALUES(@NOMBRE_CAT)
END
GO


