USE ELEARNING
GO

SELECT * FROM CURSOS

/*INSERTANDO A CATEGORIAS*/
INSERT INTO CATEGORIAS(NOMBRE_CAT) VALUES ('Informatica')
INSERT INTO CATEGORIAS(NOMBRE_CAT) VALUES ('Matematicas')
INSERT INTO CATEGORIAS(NOMBRE_CAT) VALUES ('Electronica')
INSERT INTO CATEGORIAS(NOMBRE_CAT) VALUES ('Idiomas')

/*INSERTANDO A CURSOS*/
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('EXCEL PARA PRINCIPIANTES',1,1)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('C# DESDE CERO',1,1)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('SQL DESDE CERO',1,1)

INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('OPERACIONES BASICAS',1,2)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('OPERACIONES CON FRACCIONES',1,2)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('FIGURAS TRIGONOMETRICAS',1,2)

INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('FUNDAMENTOS DE ELECTRONICA',1,3)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('RAMAS DE LA ELECTRONICA',1,3)
INSERT INTO CURSOS(NOMBRE_CURSO,ESTADO,ID_CATEGORIA) VALUES('ELECTRONICA PARA LA VIDA DIARIA',1,3)

/*INSERTANDO A TEMAS*/
INSERT INTO TEMAS(NOMBRE_TEMA,ID_CATEGORIA,ID_CURSO) VALUES('QUE ES SQL',1,3)

/*INSERTANDO POR MEDIO DE STOREPROCEDURE A USUARIOS*/
EXEC INSERTAR_USUARIOS 'VICKY','MFIGUEROA','MANUEL','FIGUEROA',33,'MASCULINO','09/01/2020','EL SALVADOR','SAN SALVADOR','75362781','2717042006@mail.utec.edu.sv','Elias2910','',1

/*INSERTANDO A PRIVILEGIOS DE USUARIO*/
INSERT INTO PRIVILEGIOS(NOMBRE_PRIVILEGIO) VALUES('ADMINISTRADOR')
INSERT INTO PRIVILEGIOS(NOMBRE_PRIVILEGIO) VALUES('ESTUDIANTE')
INSERT INTO PRIVILEGIOS(NOMBRE_PRIVILEGIO) VALUES('TUTOR') 

/*INSERTANDO A INSCRIPCIONES*/
EXEC INSERTAR_INSCRIPCIONES 0,2,3

/*INSERTANDO A TEMAS*/
EXEC INSERTAR_TEMAS 'HISTORIA DE SQL',1,3

/*INSERTANDO A CONTENIDOS*/
EXEC INSERTAR_CONTENIDOS 'Definicion del Lenguaje','Texto',1,3,1
EXEC INSERTAR_CONTENIDOS 'Caracteristicas Generales','Texto',1,3,1
EXEC INSERTAR_CONTENIDOS 'Usos de SQL','Video',1,3,1
EXEC INSERTAR_CONTENIDOS 'Usos de SQL','Imagen',1,3,1


