USE ELEARNING
GO

CREATE PROCEDURE INSERTAR_CURSO
(
	@NOMBRE_CURSO	VARCHAR(25) NOT NULL,
	@ESTADO			BIT,
	@ID_TEMA		INT
)
AS 
BEGIN
	INSERT INTO CURSO(NOMBRE_CURSO,ESTADO,ID_TEMA)
	VALUES(@NOMBRE_CURSO,@ESTADO,@ID_TEMA)
END
GO

CREATE PROCEDURE MODIFICAR_CURSO
(
	@ID_CURSO		INT,
	@NOMBRE_CURSO	VARCHAR(25) NOT NULL,
	@ESTADO			BIT,
	@ID_TEMA		INT
)
AS
BEGIN
	UPDATE CURSO
	SET
		NOMBRE_CURSO	= @NOMBRE_CURSO,
		ESTADO			= @ESTADO,
		@ID_TEMA		= @ID_TEMA
	WHERE
		ID_CURSO = @ID_CURSO
END
GO

CREATE PROCEDURE ELIMINAR_CURSO
(
	@ID_CURSO	INT
)
AS BEGIN
	UPDATE CURSO SET ESTADO = 0 WHERE ID_CURSO = @ID_CURSO
END
GO

CREATE PROCEDURE CONSULTAR_CURSO
AS BEGIN
	SELECT
		ID_CURSO,
		NOMBRE_CURSO,
		ESTADO,
		ID_TEMA
	FROM 
		CURSO
END 