USE ELEARNING
GO

CREATE PROCEDURE INSERTAR_ESTADO_USUARIO
(
	@NOMBRE_ESTADO	VARCHAR(25) NOT NULL
)
AS BEGIN
	INSERT INTO ESTADO_USUARIO(NOMBRE_ESTADO) VALUES(@NOMBRE_ESTADO)
END
GO

CREATE PROCEDURE MODIFICAR_ESTADO_USUARIO
(
	@ID_ESTADO	INT,
	@NOMBRE_ESTADO	VARCHAR(25) NOT NULL
)
AS BEGIN
	UPDATE ESTADO_USUARIO SET NOMBRE_ESTADO = @NOMBRE_ESTADO WHERE ID_ESTADO = @ID_ESTADO
END
GO

CREATE PROCEDURE ELIMINAR_ESTADO_USUARIO
(
	@ID_ESTADO INT
)
AS BEGIN
	DELETE FROM ESTADO_USUARIO WHERE ID_ESTADO = @ID_ESTADO
END
GO

CREATE PROCEDURE CONSULTAR_ESTADO_USUARIO
AS BEGIN
	SELECT
		ID_ESTADO,
		NOMBRE_ESTADO
	FROM 
		ESTADO_USUARIO
END
GO