USE ELEARNING
GO

CREATE PROCEDURE INSERTAR_USUARIO
(
	@COD_USUARIO	VARCHAR(15),
	@NOMBRE			VARCHAR(50),
	@APELLIDO		VARCHAR(50),
	@EDAD			INT,
	@SEXO			VARCHAR(10),
	@FECHA_NAC		DATE,
	@PAIS			VARCHAR(15),
	@DEPTO			VARCHAR(20),
	@TELEFONO		VARCHAR(15),
	@EMAIL			VARCHAR(25),
	@PASWORD		VARCHAR(15)
)
AS
BEGIN
	DECLARE @FECHAREGISTRO DATE
	SELECT @FECHAREGISTRO = GETDATE()

	INSERT INTO USUARIO
	(
		COD_USUARIO,	NOMBRE,		APELLIDO,	EDAD,		SEXO,	FECHA_NAC,	PAIS,
		DEPTO,			TELEFONO,	EMAIL,		PASWORD,	FECHAREGISTRO
	)
	VALUES
	(
		@COD_USUARIO,	@NOMBRE,	@APELLIDO,	@EDAD,		@SEXO,	@FECHA_NAC,	@PAIS,
		@DEPTO,			@TELEFONO,	@EMAIL,		@PASWORD,	@FECHAREGISTRO
	)

END
GO

CREATE PROCEDURE MODIFICAR_USUARIO
(
	@COD_USUARIO	VARCHAR(15),
	@NOMBRE			VARCHAR(50),
	@APELLIDO		VARCHAR(50),
	@EDAD			INT,
	@SEXO			VARCHAR(10),
	@FECHA_NAC		DATE,
	@PAIS			VARCHAR(15),
	@DEPTO			VARCHAR(20),
	@TELEFONO		VARCHAR(15),
	@EMAIL			VARCHAR(25),
	@PASWORD		VARCHAR(15)
)
AS BEGIN
	UPDATE USUARIO
	SET	
		NOMBRE			= @NOMBRE,		
		APELLIDO		= @APELLIDO,	
		EDAD			= @EDAD,		
		SEXO			= @SEXO,	
		FECHA_NAC		= @FECHA_NAC,	
		PAIS			= @PAIS,
		DEPTO			= @DEPTO,
		TELEFONO		= @TELEFONO,
		EMAIL			= @EMAIL,
		PASWORD			= @PASWORD
	WHERE
		COD_USUARIO = @COD_USUARIO
END
GO

CREATE PROCEDURE ELIMINAR_USUARIO
(
	@COD_USUARIO VARCHAR(15)
)
AS
BEGIN
	DELETE FROM USUARIO WHERE COD_USUARIO = @COD_USUARIO
END 
GO

CREATE PROCEDURE CONSULTAR_USUARIO
AS
BEGIN
	SELECT
		COD_USUARIO,	
		NOMBRE,		
		APELLIDO,	
		EDAD,
		SEXO,	
		FECHA_NAC,	
		PAIS,
		DEPTO,			
		TELEFONO,	
		EMAIL,		
		PASWORD,	
		FECHAREGISTRO
	FROM 
		USUARIO
END
GO