USE ELEARNING
GO

CREATE PROCEDURE INSERTAR_CATEGORIA
(
	@NOMBRE_CAT		VARCHAR(25) NOT NULL
)
AS BEGIN
	INSERT INTO CATEGORIA(NOMBRE_CAT) VALUES(@NOMBRE_CAT)
END
GO

CREATE PROCEDURE MODIFICAR_CATEGORIA
(
	@ID_CATEGORIA	INT,
	@NOMBRE_CAT		VARCHAR(25) NOT NULL
)
AS BEGIN
	UPDATE CATEGORIA
	SET	
		NOMBRE_CAT = @NOMBRE_CAT
	WHERE
		ID_CATEGORIA = @ID_CATEGORIA
END
GO

CREATE PROCEDURE ELIMINAR_CATEGORIA
(
	@ID_CATEGORIA	INT
)
AS BEGIN
	DELETE FROM CATEGORIA WHERE ID_CATEGORIA = @ID_CATEGORIA
END
GO

CREATE PROCEDURE CONSULTAR_CATEGORIA
AS BEGIN
	SELECT
		ID_CATEGORIA,
		NOMBRE_CAT
	FROM 
		CATEGORIA
END
GO
