ALTER PROCEDURE [dbo].[MODIFICAR_USUARIOS]
(	 
	@CODIGO_USUARIO	   VARCHAR(15),
	@NOMBRE_USUARIO	   VARCHAR(50),
	@APELLIDO_USUARIO	VARCHAR(50),
	@EDAD_USUARIO      INT,
	@SEXO_USUARIO     VARCHAR(15),
	@FECHA_NAC_USUARIO  DATE,
	@PAIS_USUARIO  VARCHAR(25),
	@DEPTO_USUARIO  VARCHAR(25),
	@TELEFONO_USUARIO VARCHAR(15),
	@EMAIL_USUARIO  VARCHAR(50),
	@PASWORD_USUARIO  VARCHAR(500),
	@IMAGEN_USUARIO VARCHAR(500),
	@ID_PRIVILEGIO_USUARIO  INT,
	@FECHAREGISTRO_USUARIO  DATETIME

)
AS 
BEGIN

	DECLARE @PASWORD VARBINARY
	SELECT @PASWORD= CAST(@PASWORD_USUARIO AS VARBINARY(MAX))

	UPDATE 
		USUARIOS
	SET
		COD_USUARIO=@CODIGO_USUARIO,
		NOMBRE=@NOMBRE_USUARIO,
		APELLIDO	=@APELLIDO_USUARIO,
		EDAD =@EDAD_USUARIO,
		SEXO=@SEXO_USUARIO,
		FECHA_NAC=@FECHA_NAC_USUARIO,
		PAIS=@PAIS_USUARIO,
		DEPTO=@DEPTO_USUARIO,
		TELEFONO=@TELEFONO_USUARIO,
		EMAIL =@EMAIL_USUARIO,
		PASWORD =@PASWORD,
		IMAGEN=CONVERT(IMAGE,@IMAGEN_USUARIO),
		ID_PRIVILEGIO=@ID_PRIVILEGIO_USUARIO,
		FECHAREGISTRO=@FECHAREGISTRO_USUARIO
	WHERE
		COD_USUARIO = @CODIGO_USUARIO
END
 
  