USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[MODIFICAR_CONTENIDOS]    Script Date: 29/11/2020 17:55:13 ******/
DROP PROCEDURE [dbo].[MODIFICAR_CONTENIDOS]
GO

/****** Object:  StoredProcedure [dbo].[MODIFICAR_CONTENIDOS]    Script Date: 29/11/2020 17:55:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[MODIFICAR_CONTENIDOS]
(
	@ID_CONTENIDO	INT,
	@DESCRIPCION	VARCHAR(100),
	@TIPO			VARCHAR(30),
	@ID_CATEGORIA	INT,
	@ID_CURSO		INT,
	@ID_TEMA		INT,
	@ARCHIVO		VARBINARY(MAX)
)
AS 
BEGIN
	UPDATE 
		CONTENIDOS
	SET
		DESCRIPCION		= @DESCRIPCION,
		TIPO			= @TIPO,
		ID_CATEGORIA	= @ID_CATEGORIA,
		ID_CURSO		= @ID_CURSO,
		ID_TEMA			= @ID_TEMA,
		ARCHIVO			= @ARCHIVO
	WHERE
		ID_CONTENIDO = @ID_CONTENIDO
END
GO


