 USE [ELEARNING]
GO


CREATE PROCEDURE [dbo].[MOSTRAR_USUARIOS]
AS 
BEGIN
	SELECT
		 U.COD_USUARIO,
		 U.NOMBRE,
		 U.APELLIDO,
		 U.EDAD,
		 U.SEXO,
		 U.FECHA_NAC AS 'FECHA DE NAC',
		 U.PAIS,
		 U.DEPTO AS DEPARTAMENTO,
		 U.TELEFONO,
		 U.EMAIL,
		 U.PASWORD,
		 U.IMAGEN,
		 P.NOMBRE_PRIVILEGIO 
	FROM 
		USUARIOS U 
		JOIN PRIVILEGIOS P ON U.ID_PRIVILEGIO=P.ID_PRIVILEGIO
END
GO
EXEC MOSTRAR_USUARIOS

 