USE [ELEARNING]
GO
/****** Object:  StoredProcedure [dbo].[MOSTRAR_CATEGORIAS]    Script Date: 6/12/2020 10:08:10 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[MOSTRAR_PRIVILEGIOS]
AS BEGIN
	SELECT
		ID_PRIVILEGIO AS CODIGO,
		NOMBRE_PRIVILEGIO AS PRIVILEGIO
	FROM 
		PRIVILEGIOS
END
