USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[MOSTRAR_CURSOS_USUARIO]    Script Date: 21/11/2020 19:21:24 ******/
DROP PROCEDURE [dbo].[MOSTRAR_CURSOS_USUARIO]
GO

/****** Object:  StoredProcedure [dbo].[MOSTRAR_CURSOS_USUARIO]    Script Date: 21/11/2020 19:21:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[MOSTRAR_CURSOS_USUARIO]
(
	@ID_USUARIO INT,
	@ID_CATEGORIA INT
)
AS 
BEGIN
	SELECT
		ID_CURSO,
		ESTADO
	INTO #USUARIO_INSCRITO
	FROM 
		INSCRIPCIONES
	WHERE
		ID_USUARIO = @ID_USUARIO

	SELECT
		C.ID_CURSO AS CODIGO,
		NOMBRE_CURSO AS NOMBRE,
		--C.ESTADO,
		CAT.NOMBRE_CAT AS DESCRIPCION,
		ISNULL(U.ESTADO,'Por Inscribir') AS ESTADO
	FROM 
				CURSOS C
	LEFT JOIN	#USUARIO_INSCRITO U ON U.ID_CURSO = C.ID_CURSO
	LEFT JOIN	CATEGORIAS CAT ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
	WHERE
		C.ID_CATEGORIA = @ID_CATEGORIA

	DROP TABLE #USUARIO_INSCRITO
END
GO


