USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[MOSTRAR_TEMAS_XCURSOS]    Script Date: 22/11/2020 17:22:46 ******/
DROP PROCEDURE [dbo].[MOSTRAR_TEMAS_XCURSOS]
GO

/****** Object:  StoredProcedure [dbo].[MOSTRAR_TEMAS_XCURSOS]    Script Date: 22/11/2020 17:22:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[MOSTRAR_TEMAS_XCURSOS]
(
	@ID_CURSO INT
)
AS
BEGIN
	SELECT
		ID_TEMA,
		NOMBRE_TEMA,
		ID_CATEGORIA,
		ID_CURSO
	FROM
		TEMAS
	WHERE
		ID_CURSO = @ID_CURSO 
END

--SELECT * FROM TEMAS WHERE ID_CURSO=3
GO