USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[REGISTRO_USUARIO]    Script Date: 6/12/2020 18:42:50 ******/
DROP PROCEDURE [dbo].[REGISTRO_USUARIO]
GO

/****** Object:  StoredProcedure [dbo].[REGISTRO_USUARIO]    Script Date: 6/12/2020 18:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[REGISTRO_USUARIO]
(
	@PATRON			VARCHAR(10),
	@COD_USUARIO	VARCHAR(15),
	@NOMBRE			VARCHAR(50),
	@APELLIDO		VARCHAR(50),
	@EDAD			INT,
	@SEXO			VARCHAR(10),
	@FECHA_NAC		DATETIME,
	@PAIS			VARCHAR(15),
	@DEPTO			VARCHAR(20),
	@TELEFONO		VARCHAR(15),
	@EMAIL			VARCHAR(25),
	@PASWORD		VARCHAR(15)
)
AS
BEGIN
	DECLARE @FECHAREGISTRO DATE, @ID_PRIVILEGIO INT , @IMAGEN VARCHAR(MAX)
	SELECT @FECHAREGISTRO = GETDATE(), @ID_PRIVILEGIO = 2, @IMAGEN='123'

	IF EXISTS(SELECT * FROM USUARIOS WHERE COD_USUARIO  = @COD_USUARIO)
	BEGIN
		SELECT -1 AS RESULTADO
	END
	ELSE
	BEGIN
		INSERT INTO USUARIOS
		(
			COD_USUARIO,	NOMBRE,		APELLIDO,	EDAD,		SEXO,	FECHA_NAC,	PAIS,
			DEPTO,			TELEFONO,	EMAIL,		PASWORD,	FECHAREGISTRO,
			IMAGEN,			ID_PRIVILEGIO
		)
		VALUES
		(
			@COD_USUARIO,	@NOMBRE,	@APELLIDO,	@EDAD,		@SEXO,	@FECHA_NAC,	@PAIS,
			@DEPTO,			@TELEFONO,	@EMAIL,		ENCRYPTBYPASSPHRASE(@PATRON, @PASWORD),	@FECHAREGISTRO,
			@IMAGEN,		@ID_PRIVILEGIO
		)

		SELECT @@IDENTITY AS RESULTADO

	END
END

GO

--EXEC REGISTRO_USUARIO 'VICKY','JFERNANDEZ','JOSE','AYALA',33,'MASCULINO','09/01/2020','EL SALVADOR','SAN SALVADOR','75362781','2717042006@mail.utec.edu.sv','Elias2910'

