USE ELEARNING
GO

ALTER PROCEDURE VALIDAR_USUARIO
(
	@PATRON			VARCHAR(10),
	@COD_USUARIO	INT,
	@PASWORD		VARCHAR(30)
)
AS 
BEGIN
	IF EXISTS(SELECT * FROM USUARIOS WHERE COD_USUARIO = @COD_USUARIO)
	BEGIN
		DECLARE @PASWORD_DECRIP VARCHAR(30)
		SELECT
			@PASWORD_DECRIP = CAST(DECRYPTBYPASSPHRASE(@PATRON, PASWORD) AS VARCHAR(MAX))
		FROM
			USUARIOS
		WHERE
			COD_USUARIO = @COD_USUARIO

		SELECT
			ID_USUARIO, COD_USUARIO, NOMBRE, APELLIDO, EDAD,SEXO,FECHA_NAC, PAIS, DEPTO,TELEFONO,EMAIL,PASWORD,IMAGEN,ID_PRIVILEGIO,FECHAREGISTRO
		FROM USUARIOS WHERE COD_USUARIO = @COD_USUARIO
	END
	ELSE
	BEGIN
		SELECT -1
	END
END
GO

--SELECT * FROM USUARIOS

