USE [ELEARNING]
GO

/****** Object:  StoredProcedure [dbo].[VALIDAR_USUARIO]    Script Date: 6/12/2020 12:40:26 ******/
DROP PROCEDURE [dbo].[VALIDAR_USUARIO]
GO

/****** Object:  StoredProcedure [dbo].[VALIDAR_USUARIO]    Script Date: 6/12/2020 12:40:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[VALIDAR_USUARIO]
(
	@PATRON			VARCHAR(10),
	@COD_USUARIO	VARCHAR(40),
	@PASWORD		VARCHAR(30)
)
AS 
BEGIN
	IF EXISTS(SELECT * FROM USUARIOS WHERE COD_USUARIO = @COD_USUARIO AND CONVERT(varchar(25),DECRYPTBYPASSPHRASE(@PATRON, PASWORD))=@PASWORD)
	BEGIN
		SELECT
			ID_USUARIO, COD_USUARIO, NOMBRE, APELLIDO, EDAD,SEXO,FECHA_NAC, PAIS, DEPTO,TELEFONO,EMAIL,PASWORD,IMAGEN,ID_PRIVILEGIO,FECHAREGISTRO
		FROM 
			USUARIOS 
		WHERE 
			COD_USUARIO = @COD_USUARIO AND CONVERT(varchar(25),DECRYPTBYPASSPHRASE(@PATRON, PASWORD))=@PASWORD
	END
	ELSE
	BEGIN
		SELECT -1 AS ID_USUARIO
	END
END
GO


